// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijNl4y_5YVJMCFLvs8xANJl_UoIqTg00',
    appId: '1:628281445808:android:0621532a9852d3251c9a75',
    messagingSenderId: '628281445808',
    projectId: 'elitelive-81772',
    storageBucket: 'elitelive-81772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW79PG54mvvA6SxuSDz-fzXbn26xoBHWw',
    appId: '1:628281445808:ios:7a7ad0cbdb35f82c1c9a75',
    messagingSenderId: '628281445808',
    projectId: 'elitelive-81772',
    storageBucket: 'elitelive-81772.firebasestorage.app',
    androidClientId: '628281445808-6rcarfi8tvkngpfsh4eboioe2qm81mra.apps.googleusercontent.com',
    iosClientId: '628281445808-9sopig57tblhtf10f1hfiar6cvngnlfi.apps.googleusercontent.com',
    iosBundleId: 'com.elitelive.mobile.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhxXKECi9lx4JHLJqDru5wp7MAjF5wWaI',
    appId: '1:628281445808:web:39a758792ca911401c9a75',
    messagingSenderId: '628281445808',
    projectId: 'elitelive-81772',
    authDomain: 'elitelive-81772.firebaseapp.com',
    storageBucket: 'elitelive-81772.firebasestorage.app',
    measurementId: 'G-8LBP6J0P5H',
  );

}